export enum ButtonType {
  NONE = 'NONE',
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  TEXT = 'TEXT'
}

export enum Color {
  AMBER = 'AMBER',
  BLUE = 'BLUE',
  CYAN = 'CYAN',
  EMERALD = 'EMERALD',
  FUCHSIA = 'FUCHSIA',
  GRAY = 'GRAY',
  GREEN = 'GREEN',
  INDIGO = 'INDIGO',
  LIME = 'LIME',
  MONO = 'MONO',
  MONO_INVERTED = 'MONO_INVERTED',
  ORANGE = 'ORANGE',
  PINK = 'PINK',
  PURPLE = 'PURPLE',
  RED = 'RED',
  ROSE = 'ROSE',
  TEAL = 'TEAL',
  VIOLET = 'VIOLET',
  YELLOW = 'YELLOW'
}

export enum ComponentName {
  ALERT = 'ALERT',
  AVATAR = 'AVATAR',
  BADGE = 'BADGE',
  BOTTOM_SHEET = 'BOTTOM_SHEET',
  BOTTOM_TABBER = 'BOTTOM_TABBER',
  BUTTON = 'BUTTON',
  CARD = 'CARD',
  CHECKBOX = 'CHECKBOX',
  COLLAPSE = 'COLLAPSE',
  COLLAPSE_CHILD = 'COLLAPSE_CHILD',
  CONTEXT_MENU = 'CONTEXT_MENU',
  DIALOG = 'DIALOG',
  DIVIDER = 'DIVIDER',
  EMPTY = 'EMPTY',
  FEEDBACK_DIALOG = 'FEEDBACK_DIALOG',
  FORM = 'FORM',
  GRID = 'GRID',
  GRID_ITEM = 'GRID_ITEM',
  HEADER = 'HEADER',
  ICON = 'ICON',
  IMAGE = 'IMAGE',
  INPUT = 'INPUT',
  INPUT_FILE = 'INPUT_FILE',
  LIST = 'LIST',
  LIST_ITEM = 'LIST_ITEM',
  MODAL = 'MODAL',
  NOTIFICATION = 'NOTIFICATION',
  NOT_FOUND = 'NOT_FOUND',
  ONBOARDING = 'ONBOARDING',
  PROGRESS = 'PROGRESS',
  RESULT = 'RESULT',
  ROUTER = 'ROUTER',
  SELECT = 'SELECT',
  SIDEBAR = 'SIDEBAR',
  SMART_LIST = 'SMART_LIST',
  SPINNER = 'SPINNER',
  SQUIRCLE = 'SQUIRCLE',
  STATISTIC = 'STATISTIC',
  SWITCH = 'SWITCH',
  TAG = 'TAG',
  TOAST = 'TOAST',
  TOP_TABBER = 'TOP_TABBER',
  VIRTUALIZED_LIST = 'VIRTUALIZED_LIST',
  WIZARD = 'WIZARD'
}

export enum DirectionHorizontal {
  LEFT = 'LEFT',
  RIGHT = 'RIGHT'
}

export enum DirectionVertical {
  DOWN = 'DOWN',
  UP = 'UP'
}

export enum DividerType {
  HORIZONTAL = 'HORIZONTAL',
  VERTICAL = 'VERTICAL'
}

export enum FeedbackType {
  ERROR = 'ERROR',
  INFORMATION = 'INFORMATION',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING'
}

export enum FormFieldType {
  CHECKBOX = 'CHECKBOX',
  INPUT = 'INPUT',
  SELECT = 'SELECT'
}

export enum InputFileMode {
  MULTIPLE = 'MULTIPLE',
  SINGLE = 'SINGLE'
}

export enum InputType {
  BUFFER = 'BUFFER',
  DATE = 'DATE',
  EMAIL = 'EMAIL',
  NUMBER = 'NUMBER',
  PASSWORD = 'PASSWORD',
  TEL = 'TEL',
  TEXT = 'TEXT',
  URL = 'URL'
}

export enum Layer {
  ZERO = 0,
  ONE = 1,
  TWO = 2,
  THREE = 3
}

export enum SelectMode {
  MULTIPLE = 'MULTIPLE',
  SINGLE = 'SINGLE'
}

export enum Shape {
  CIRCLE = 'CIRCLE',
  NONE = 'NONE',
  RECTANGLE = 'RECTANGLE',
  SQUARE = 'SQUARE',
  SQUIRCLE = 'SQUIRCLE'
}

export enum Theme {
  DARK = 'DARK',
  LIGHT = 'LIGHT',
  SYSTEM = 'SYSTEM'
}
